"""Add open time

Revision ID: 31fc6e9e2894
Revises: 81d3a0766755
Create Date: 2025-10-27 19:29:30.902996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31fc6e9e2894'
down_revision: Union[str, Sequence[str], None] = '81d3a0766755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('open_time', sa.Time(), nullable=True))
    op.add_column('stores', sa.Column('close_time', sa.Time(), nullable=True))
    op.add_column('stores', sa.Column('is_closed_today', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'is_closed_today')
    op.drop_column('stores', 'close_time')
    op.drop_column('stores', 'open_time')
    # ### end Alembic commands ###
