"""Add ordertitle

Revision ID: 6a65399c0bde
Revises: 1c5e7f23b3e9
Create Date: 2025-10-26 10:28:48.358833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a65399c0bde'
down_revision: Union[str, Sequence[str], None] = '1c5e7f23b3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_title')
    # ### end Alembic commands ###
