"""added store_id to orders

Revision ID: 723b9158f0c0
Revises: 
Create Date: 2025-10-16 13:07:57.448158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '723b9158f0c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'])
    # op.alter_column('stores', 'image',
    #            existing_type=mysql.LONGTEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    # op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.alter_column('stores', 'image',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'store_id')
    # ### end Alembic commands ###
