"""Add contact_number to orders

Revision ID: 81d3a0766755
Revises: 18b4bad461f0
Create Date: 2025-10-26 11:08:59.203988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d3a0766755'
down_revision: Union[str, Sequence[str], None] = '18b4bad461f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'contact_number')
    # ### end Alembic commands ###
