"""added contact_number to store

Revision ID: 915f86574f1b
Revises: f7be41b5bbdf
Create Date: 2025-10-21 21:09:35.072601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915f86574f1b'
down_revision: Union[str, Sequence[str], None] = 'f7be41b5bbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('contact_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'contact_number')
    # ### end Alembic commands ###
