"""added store name

Revision ID: f6948c1013d5
Revises: 915f86574f1b
Create Date: 2025-10-24 11:04:22.539239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6948c1013d5'
down_revision: Union[str, Sequence[str], None] = '915f86574f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('store_name', sa.String(255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'store_name')
    # ### end Alembic commands ###
