"""added few tables

Revision ID: 03e25ed971f1
Revises: afa9742e11ab
Create Date: 2025-11-10 12:40:41.884463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e25ed971f1'
down_revision: Union[str, Sequence[str], None] = 'afa9742e11ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_delivery_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=True),
    sa.Column('per_km_fee', sa.Float(), nullable=True),
    sa.Column('min_fee', sa.Float(), nullable=True),
    sa.Column('max_fee', sa.Float(), nullable=True),
    sa.Column('reduce_fee_below_50', sa.Float(), nullable=True),
    sa.Column('reduce_fee_below_100', sa.Float(), nullable=True),
    sa.Column('free_above', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_delivery_settings_id'), 'app_delivery_settings', ['id'], unique=False)
    op.create_table('product_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_subcategories_id'), 'product_subcategories', ['id'], unique=False)
    op.add_column('products', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    op.drop_index(op.f('ix_product_subcategories_id'), table_name='product_subcategories')
    op.drop_table('product_subcategories')
    op.drop_index(op.f('ix_app_delivery_settings_id'), table_name='app_delivery_settings')
    op.drop_table('app_delivery_settings')
    # ### end Alembic commands ###
