"""your change

Revision ID: 0798ee543d13
Revises: 8c84928d2e93
Create Date: 2025-11-09 23:23:43.393118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0798ee543d13'
down_revision: Union[str, Sequence[str], None] = '8c84928d2e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'longitude')
    op.drop_column('stores', 'latitude')
    # ### end Alembic commands ###
