"""added few tables

Revision ID: c545a8bd132e
Revises: 91158ff3ba05
Create Date: 2025-11-10 16:47:57.056275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c545a8bd132e'
down_revision: Union[str, Sequence[str], None] = '91158ff3ba05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('store_earnings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'store_earnings')
    # ### end Alembic commands ###
