"""added few tables

Revision ID: f2ea42c00cef
Revises: 03e25ed971f1
Create Date: 2025-11-10 13:28:35.207219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2ea42c00cef'
down_revision: Union[str, Sequence[str], None] = '03e25ed971f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # op.alter_column('users', 'role',
    #            existing_type=mysql.VARCHAR(length=50),
    #            type_=sa.Enum('superadmin', 'store_owner', 'user', name='user_roles'),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('superadmin', 'store_owner', 'user', name='user_roles'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
